### ISSUE TITLE
Tech Spike - NGCP Docs Website Solution

### ISSUE THREAD

**Issue by marked01one** [Northrop-Grumman-Collaboration-Project/progress-board-tracker#86]
**Goal:** Test around with Astro Docs to confirm whether or not it is a viable solution for an NGCP docs hub. Specifically, whether it can do the following:
- Be deployed on GitHub Pages via Github Actions.
- Have a way for non-programmers to edit and change the, or if there is a way we can implement such functionaility.
- Automation tools for documenting UI/DB/VI codebases.
- Can you automatically update the docs site directory structure (the tree list of pages)?
- How customizable is the UI styles? Are there pre-made themes that can be used to simplify our tasks?
- What extra functionalities makes it good as a place to document not only code & troubleshooting details.
- Can you embed the ability to download files on it (far fetch).

**Comment by Leaversa** [comment]
> Be deployed on GitHub Pages via Github Actions.

Yes this is supported out of the box and is well [documented](https://docs.astro.build/en/guides/deploy/github/).

> Have a way for non-programmers to edit and change them, or if there is a way we can implement such functionality.

Editing files can be done by utilizing markdown (md/mdx).  As long as non-programmers are familiar with how to push and pull from github and editing markdown files, there wouldn't be any issue adding to the documentation.  More details [here](https://docs.astro.build/en/guides/markdown-content/).

> Automation tools for documenting UI/DB/VI codebases.

There are several plugins that support automatic documentation. For frontend, an option for typescript would be [starlight-typedoc](https://github.com/HiDeoo/starlight-typedoc). For backend or other non-typescript languages, an option would be [starlight-openapi](https://github.com/HiDeoo/starlight-openapi).

> Can you automatically update the docs site directory structure (the tree list of pages)?

Page and documentation structure is defined and autogenerated by [folder structure](https://docs.astro.build/en/guides/routing/) (as long as the specific folder is defined in config before hand).

> How customizable is the UI styles? Are there pre-made themes that can be used to simplify our tasks?

UI styles are completely [customizable](https://starlight.astro.build/guides/css-and-tailwind/) with support for both tailwindcss and vanilla css. The pre-made theme that is used fits well and I believe it isn't necessary to change anything.

> What extra functionalities makes it good as a place to document not only code & troubleshooting details.

It is extremely flexible and easy to use since it uses frontmatter and [layouts](https://docs.astro.build/en/basics/layouts/). It is optimized well for a documentation site since it is used primarily for static sites but has support for embedded client-side frontend framework components on a static site using the [islands architecture](https://docs.astro.build/en/concepts/islands/). This is ideal for frontend because it allows frontend to embed interactive components directly into its documentation page without compromising on the primary use case of static site generation.

Additionally it extends the same markdown approach used in the previous documentation site. So adding content like images, links, sections, etc. can be done the same way. However there are already included [components ](https://starlight.astro.build/guides/components/) that allow for more clarity in the documentation pages without requiring much knowledge about Astro.

> Can you embed the ability to download files on it (far fetch).

Unsure by what this means or what it would look like for a documentation site? @marked01one

**Comment by marked01one** [comment]
Since the docs website is up and working, I'm closing this issue. Please make new issues for any future development with the NGCP Docs site.
